<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Error during topic updation' => 'Ошибка во время обновления темы',
  'Error has been occured during topic updation: `{message}`' => 'Произошла ошибка по время обновления темы: `{message}`',
  'Topic `{topic}` has been updated' => 'Тема `{topic}` обновлена',
  'Topic `{topic}` has been updated at {timestamp}.' => 'Тема `{topic}` обновлена {timestamp}.',
);
